Base:
  HttpPort: 1926

App:
  AppID: "{Set your app id here.}"
  AppSecret: "{Set your app password here.}"

Mongo: 
  DBName: "goodsman2"
  User: "admin"
  Pwd: "{Set your db password here.}" 
  Host: "localhost"
  Port: 27017